WICG/webmonetization

website/static/css/custom.css

Gives the provider cards a move clickable feel.

feat: provider card hover state

---

website/static/examples/events.html

Just adding this page to examples for now but it's a useful test to measure how well WM is working in your browser. Can polish it up later and link to from the rest of the site

feat: add events test page

---

docs/ilp-wallets.md
docs/stronghold.md

Added note about Stronghold's limited availability.

fix: add note about stronghold limited availability

---

website/siteConfig.js

Our config is at: https://github.com/algolia/docsearch-configs/blob/master/configs/webmonetization.json

feat: add search

---

docs/ilp-wallets.md

Just need to follow the docs at: 
https://v2.docusaurus.io/docs/markdown-features#assets

fix: uphold and gatehub images

---

src/pages/index.js

doc: updated links on main page

---

workers/exclusive-content/.gitignore
workers/exclusive-content/package.json
workers/exclusive-content/src/index.ts
workers/exclusive-content/wrangler.toml
workers/exclusive-content/wrangler.toml.example

just did a few fixes so that 'wrangler publish' would work. I've published the worker in it's current state to webmonetization.org (the route is `https://webmonetization.org/api/exclusive-content/*` as written in wrangler.toml) so that you can more easily test the frontend.

feat: fix up exclusive content worker to make publishable

---

docs/receipt-verifier.md

Decided to leave the monetizationprogress event listener section as-is

docs: add info about publicly available verifier

---

.circleci/config.yml

yml github

---

docusaurus.config.js

fix: add missing comma

---

.github/workflows/tidy.yml
static/specification.html
static/tidyconfig.txt

Makes it easier for folks to contribute, without worrying about worrying about whitespace. Checks HTML for us too.  
This will make it easier to review all other PRs too.

Chore: enable auto-tidy of spec on PRs

---

workers/exclusive-content/README.md
workers/exclusive-content/package.json
workers/exclusive-content/rollup.config.js
workers/exclusive-content/wrangler.toml
workers/exclusive-content/yarn.lock
workers/probabilistic-revshare/wrangler.toml
workers/receipt-verifier/wrangler.toml

Updates Exclusive Content Generator to use Wrangler 2
- related to #295

chore: ECG - use wrangler 2

---

src/pages/exclusive-content.js
src/pages/meta-tag.js
src/pages/prob-revshare.js

Cherry-picked from https://github.com/WICG/webmonetization/pull/313 to resolve issue on main branch as well.

Fix import path for Link component

---

.github/ISSUE_TEMPLATE/feature_request.md

This PR adds another issue template to the repository.

Add `feature-request` issue template

---

.github/actions/get-contributors.js
.github/workflows/contributors.yml

After messing around in a test repo, I finally figured out the correct YML steps for the thing to run correctly (see https://github.com/huijing/octokit-test/actions)

Resolve github actions failure

---

docs/web-monetization-api.md
docusaurus.config.js
static/specification-respec.html
static/specification/index.html
static/specification/versions/CG-DRAFT-web-monetization-20210317.html

Resolves all broken links on the list in the issue.

Fix broken links

---

docs/counter.md

Update micropayments counter guide

---

package.json
src/styles/docs.css

This PR updates the styles from the default Starlight theme to our new ILF docs theme.

Update default theme with ILF theme

---

package.json
src/env.d.ts
src/overrides/Header.astro
src/styles/ilf-docs.css

Closes #387 
This PR updates Starlight and Astro to the latest versions and makes the relevant updates due to the introduced API changes (just CSS class renaming)

Update to latest starlight

---

package.json
src/overrides/Header.astro

This PR bumps Starlight up to v0.10.0

chore: update to latest version of Starlight

---

src/styles/ilf-docs.css

This PR syncs up the shared theme file we use across all Starlight docs sites.

chore: sync base theme with other Starlight docs

---

package.json
src/components/docs/BrowserCompat.astro

This PR bumps up project dependencies to the latest version.

chore: bump dependencies

---

package.json
src/content/docs/docs/intro/web-monetization-flow.mdx

The dependencies have not been updated for a while and it's time for a regularly scheduled bump.

chore: update dependencies again

---

README.md

Includes other minor content updates

docs: update readme (fixes #412)

---

CONTRIBUTING.md
README.md

We put off merging PRs for too long and everyone touched all the files plus prettier and all the things, TLDR much conflict. After fixing conflicts on the individual PRs, this should finally wrap up all the changes.
Or not.
乁⁠(⁠ ⁠•⁠_⁠•⁠ ⁠)⁠ㄏ
Let's merge PRs quickly next time.

chore: Resolve all the conflicting changes from the past 4 PRs

---

astro.config.mjs
src/content/docs/fr/docs.mdx

Init French language for the documentation. 
- Related issue : #427 
- Related topic : i18n

i18n(fr): Add `docs/index` in French language

---

src/content/docs/docs/guides/set-up-probabilistic-revenue-sharing.mdx
tsconfig.json
workers/probabilistic-revshare/tsconfig.json

Minor edits to the probabilistic revenue sharing guide to align with wallet address convention

372 - probabilistic revenue sharing fix

---

README.md

Added info on call plus link to add to calendar.

Update README.md to include catchup call details

---

astro.config.mjs
src/content/docs/docs/resources/get-involved.mdx

Added "Get Involved" page and content
Amended left nav to include new page

Added "Get Involved" page

---

astro.config.mjs
package.json

This PR updates all latest dependencies and hence is able to add the external link icon to sidebar items. It also cleans up some links we deemed unnecessary.

chore: update sidebar with new external link icon

---

src/components/docs/Specification.astro

This fixes our specification table styles after Starlight changed their table styling in https://github.com/withastro/starlight/commit/c5b47cbe1242f0b29b9212db72fe26590ab57d88

fix: adjust spec table spacing

---

src/content.config.ts

@huijing sorry I missed this part of the upgrade.

deps: update starlight part of config file

---

src/content/docs/docs/references/activitystreams.mdx

I clarified the language of the JSON-LD usage based on feedback received during FOSDEM.
- Corrected terminology
- Explained when to add a wallet address to a user and when to add it to a post directly
- Added example with multiple wallet addresses

docs: clarify JSON-LD usage

---

src/pages/specification/index.html
src/pages/specification/specification-respec.html

- Fix ReSpec usage and a broken link (just in case, I'm maintainer of ReSpec)
- Link back to openpayments.dev instead of openpayments.guide
- Run tidy, and re-generate spec.

fix(spec): fix ReSpec usage and a broken link

---

src/pages/tools/index.astro

take publisher tools down for maintenance

fix(/tools): down for maintenance

---

src/pages/tools/index.astro

Reverts WICG/webmonetization#513

Revert "fix(/tools): down for maintenance"

---

src/content/docs/resources/get-involved.mdx

- Updated the Get Involved page with format and style consistent with that of the OP and Rafiki pages

docs: mi/update-get-involved

---

src/content/docs/tutorials/contribution-counter.mdx
src/content/docs/tutorials/remove-content.mdx
src/content/docs/tutorials/revenue-sharing.mdx
src/content/docs/tutorials/show-content.mdx

Added banner to guides that call Glitch so people know the interactive examples are not working.

docs: add banner to glitch guides
