WICG/webmonetization

website/static/js/custom.js
website/static/service-worker.js

Previous site had a service worker.
Having no service worker anymore causes issues for people who loaded the site previously
https://github.com/w3c/ServiceWorker/issues/204

add a no-op service worker for previous installations

---

docs/counter.md
docs/exclusive-content.md
docs/remove-ads.md
docs/show-content.md
docs/start-stop.md
website/i18n/en.json
website/sidebars.json
website/static/examples/counter.html
website/static/examples/remove_ads.html
website/static/examples/show.html
website/static/examples/show_simple.html
website/static/examples/start-stop.html

Added some examples on how to do exclusive content with Web Monetization. Also included the examples in the static folder so users can try them out.
edit: also added a remove ads example
edit: added example counter and start/stop wm example

docs: add web monetization examples

---

website/pages/en/index.js

Fabian made me aware of the fact that it is "Web Monetization" on the entire page.
Sorry for not paying attention to detail.

fix: make spelling consistent with rest of the page

---

website/siteConfig.js

Removed link to plugin by @mrmuhammadali as the logo is expanding beyond the borders of the button.

fix: hide gatsby tool until logo is fixed

---

src/page-support/prob-revshare/components/active-view.js
src/page-support/prob-revshare/components/only-client.js

Fixes a server-side rendering bug that appeared on the live site, where a reload would trigger the server-side rendered page to not match the client-side rendered page due to the lack of localstorage. This change defers the loading of the chart and meta tag until it renders on the client-side, sidestepping this issue.

fix: only render stateful components once app is hydrated

---

src/page-support/prob-revshare/lib/index.js
workers/probabilistic-revshare/src/lib/pointers.ts

Suggestion from Stefan, uses the payment pointer form in the meta tag instead of the url form (`http://webmonetization.org...`) to be clearer for users. As a consequence, the share data must be moved into the path instead of the query string, as query strings are forbidden in payment pointer form.

feat: use payment pointer instead of url form for revshare

---

static/specification.html

Other text in the spec indicates that progress is tied to the progress event, not the start event.

Fix event typo

---

README.md
docs/stronghold.md
docusaurus.config.js
src/pages/index.js
static/specification.html

This PR performs the following minor chores/fixes:
* updates a number of broken links
* updates links to the docusaurus site to the v2 docusaurus docs
* updates the README to reflect the updated docusaurus version
The recent update from docusaurus v1 to v2 appears to have broken a number of links as the content has been rearranged. Whilst addressing those I also found the README required updating as it still reflected v1 structure.
local testing was successful

Resolve Broken Links & Update Docusaurus Refs

---

workers/receipt-verifier/src/index.ts

passes the origin along to the receipt verifier so that it returns the CORS headers

feat: pass on origin

---

docs/getting-started.md
docs/glossary.md

I'm finding that some links break for me, and when I go back from the error page, the link then works properly. I've updated two pages to try and solve the issue.

doc: investigate broken links

---

docs/uphold.md
static/css/custom.css

I tried to rig the GIFs on the Uphold page to have a 1px border so they were more visible, but the files ended up breaking

docs: fix broken uphold gifs

---

workers/exclusive-content/src/lib/helpers.ts
workers/exclusive-content/src/lib/receiptVerifier.ts

Since a cloudflare worker cannot call another cloudflare worker, we change the verifier URL to the google cloudrun URL to talk to the verifier directly and not via the cloudflare worker. 
This needs to be deployed to cloudflare after merging.

feat: use google cloudrun verifier to avoid worker to worker call 

---

.github/workflows/publish-workers.yml

This requires a CloudFlare API token with workers edit permissions to be [added as a repository secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) named `CF_API_TOKEN`.
I have a token but don't have permissions to create secrets for this repo.

chore: deploy Cloudflare workers on push to master

---

docusaurus.config.js

@justmoon suggested to also add the exclusive content generator to the footer where all the other generators are linked.

feat: add link to exclusive content generator to footer

---

static/specification.html

Removed references to SPSP
Deprecated the receipt attribute of monetization event
The major change here is for the UA to use Open Payments to send payments rather than directly creating a STREAM connection.
The presumption is that the user has configured two services in the UA, a WM Provider (e.g. Coil) and their Open Payments enabled wallet (e.g. Uphold).
- The WM Provider provides the configuration for how much to pay, who to pay etc
- The wallet exposes [Open Payments APIs](https://docs.openpayments.guide) and during enrolment the browser stores access tokens that it can use to invoke these APIs on behalf of the user (e.g. to create an outgoing payment from the user's account).
The flow would be something like this:
1. User visits a website and the UA parses the Open Payments account …

Updates to support Open Payments

---

static/specification.html

Need to monkey patch BigInt.prototype.toJSON for JSON.stringify to work
```typescript
export function extendPrimitives(): void {
// Extend BigInt prototype for easier JSON stringification
Object.defineProperty(BigInt.prototype, 'toJSON', {
value: function (): string {
return this.toString()
}
})
}
```
All operands must be BigInt in math operations
```
> BigInt(0) / 5
Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
```
It is only a Big *Integer*, not an arbitrary precision, floating point Decimal. This means that when converting to floating point one must use number math. When using BigInt math, fractional amounts will round down to zero.
```
> const amount = BigInt(1)
> const assetScale = 2
> const assetCode = 'USD'
> console.log(`${assetCode}${amount / …
```

fix: revert ill considered bigint usage for amount

---

static/specification.html

I have tried to address some of the discussion in the main link_rel PR. I think that this helps to make the whole spec a little cleaner.
The goal is that the WM spec should not have too much detail about ILP or Open Payments as these are evolving and leaking details into this spec makes changes hard.
fix: math in examples
As pointed out by @sublimator 
fix: payment pointer (not endpoint)
Replace "payment end-point" with payment pointer
fix: send amount in event
Fix ambiguity about send vs receive amount and add warning about changes
fix: removed some leaking external protocol refs
Adjust some wording to remove ambiguity about Open Payments concepts.
fix: former editors, editor details
Move former editors into former editors block

fix: various

---

src/pages/exclusive-content.js
src/pages/meta-tag.js
src/pages/prob-revshare.js

Closes https://github.com/WICG/webmonetization/issues/312
This PR resolves the error caused by `Link` component not imported correctly, hence causing the build to fail. Pages render as expected after updating the import path.
`BrowserOnly` is unnecessary and was removed.

Fix import path for Link component

---

src/pages/meta-tag.js

I have a typo on one of the links on the Link Tag Generator page that requires fixing. It involves the deletion of an errant slash.

Fix broken link causing CI failure

---

static/css/custom.css

The previous update to the site styles have made the font sizing on the docs pages a tad too big. Moving the base font size change to impact ONLY the custom React pages. This also resolves the issue of the font size on the navbar causing the icons to wrap just before the breakpoint hits.
Problem:
Fix:
Problem:
Fix:

Apply variable font sizing only to React pages

---

src/pages/index.js

Closes #334 
This PR fixes the "Page not found" issue with the 2 links in the Resources section. Upon further inspection, it seems that the first 3 links are incorrect and this has been rectified as well.
FYI, the specification, although accessible at https://webmonetization.org/specification.html, is not actually part of the SPA pages generated by Docusaurus, therefore we need to utilise the escape hatch of `pathname://` to resolve this (see https://docusaurus.io/docs/advanced/routing#escaping-from-spa-redirects)
**🎩 Top-hatting instructions (i.e. human testing that things are not broken)**
1. Pull this branch
2. Go to http://localhost:3000/ and scroll to the resources section. Verify that all links are working correctly.

Update links in Resources section

---

docs/monetization-src.md
docs/permission-policy-monetization.md
docs/permission-policy.md

Closes #352
Permissions policy pages used the old syntax. Updated to new. Also fixed typo in the CSP monetization-src page.

Update permissions policy syntax

---

docs/permission-policy.md
static/specification-respec.html
static/specification/index.html

Closes #244 
This PR adds a note that explains the adding or removing the monetization attribute has no effect on an already-loaded document.
**🎩 Top-hatting instructions (i.e. human testing that things are not broken)**
1. Pull down this branch
2. Navigate to http://localhost:3000/specification.html#permissions-policy and check that the note is rendering correctly (or you could probably use the deploy preview since we turned that on ¯\\\_(ツ)_/¯)

Add note for allow attribute

---

src/pages/link-tag/index.js

Closes #322 
This PR updates the default example on the link tag generator page from 
```
<link rel="monetization" href="$YourPaymentPointer" />
```
to
```
<link rel="monetization" href="https://YourPaymentPointer" />
```

Update default example in link tag generator

---

docusaurus.config.js
src/pages/index.js

Closes #364 
This PR turns on search by adding the required configuration options in the docusaurus config file.
**🎩 Top-hatting instructions (i.e. human testing that things are not broken)**
1. Pull down this branch
2. Navigate to http://localhost:3000/ (or you could probably use the deploy preview since we turned that on ¯\\\_(ツ)_/¯) and click on the search bar in the top right corner
3. The overlay should pop-up without errors, and if you start typing, there should be results showing up until you reach a string that we do not have indexed

Turn on search

---

src/components/docs/Tooltip/Tooltip.module.css
src/styles/docs.css

Closes #375 
This PR makes the height of the side nav 100% and makes the border of the tooltip more obvious against the dark background.

Fix styling issues

---

.github/workflows/contributors.yml

This PR updates the contributors.yml workflow such that it creates a PR instead of trying to merge directly to main, which fails because it is a protected branch.

fix: add git branching to contributors workflow

---

package.json
src/components/docs/LargeImg/LargeImg.module.css
src/components/docs/MermaidWrapper/MermaidWrapper.module.css
src/styles/ilf-docs.css

This PR fixes the side navigation scrolling issue by adding a height to the navigation container and adds some default styles to images on the docs.

fix: resolve issues raised in #384

---

astro.config.mjs
package.json

This PR bumps dependencies and removes unnecessary rehype plugin (it doesn't actually do anything)

chore: regularly scheduled dependency updates

---

astro.config.mjs
src/content/docs/es/docs.mdx

Part of #401 
This is a replacement PR for #420 which takes the content from that PR and resolves the incorrect configuration issues.
To test this PR:
1. Go to https://deploy-preview-422--webmonetization-preview.netlify.app/docs/, there should be a language switcher dropdown now
2. Select Español and you should see the Spanish content rendered, with the tooltips also translated (the direct link to the page should be https://deploy-preview-422--webmonetization-preview.netlify.app/es/docs/)

feat: add Spanish translation for Intro page

---

src/pages/specification/index.html
src/pages/specification/specification-respec.html

Currently, the links in the warning block use relative paths which end up being broken. This PR updates them to use absolute paths instead.

fix: change paths in warning message to absolute paths

---

package.json

This PR bumps dependencies to the latest versions, notably the 0.21.1 version of Starlight which contains the `<Steps>` component that we'd like to utilise.

chore: bump dependencies to latest version

---

src/content/docs/docs/references/attributes/incomingpayment.mdx
src/pages/specification/includes/verify-payment-example.js

`Response.json()` returns a promise to parsed JSON.

fix: update examples with fetching `incomingPayment`

---

astro.config.mjs
package.json
src/content/docs/docs.mdx
src/content/docs/docs/references/attributes/amount.mdx
src/content/docs/docs/references/attributes/assetcode.mdx
src/content/docs/docs/references/attributes/assetscale.mdx
src/content/docs/docs/references/attributes/incomingpayment.mdx
src/content/docs/docs/references/attributes/receipt.mdx
src/content/docs/es/docs.mdx

feat: add links validator and update links

---

astro.config.mjs
package.json
src/components/docs/PageSidebar.astro
src/components/docs/PageTitle.astro

This PR adds 2 override components:
1. PageTitle: move the updated date from the bottom of the page to the top
2. PageSidebar: remove the "Overview" as the first item of the right sidebar ToC

feat: add PageTitle and PageSidebar override

---

src/components/docs/PageSidebar.astro

Fix PageSidebar to handle undefined `toc` gracefully so that when it is undefined we do not add an items array since in that instance it would violate the toc's type.

fix: Handle undefined  in PageSidebar component

---

src/pages/welcome.astro

Closes #481 
Closes https://github.com/interledger/web-monetization-extension/issues/738

feat(/welcome): add messages for new intents and results

---

package.json
src/layouts/Base.astro

There have been a few difficulties with this dependency bump.
Firstly, Starlight, as of now, has a compatibility issue with astro@5. This is being addressed (see [https://github.com/withastro/starlight/pull/2612](https://github.com/withastro/starlight/pull/2612))
Secondly, bumping up the @astrojs/starlight dependency caused compatibility issues with the `HeadHrefLangs` component that is part of the astro-i18next module. Unfortunately, it seems this module is no longer being maintained. As such, I've removed it for now. HeadHrefLangs is a component from astro-i18next that generated <link> tags with hreflang attributes for SEO, specifying alternate language versions of a webpage. This means we need to investigate a new way to build this in and probably use either a different community based …

chore: basic dependency bump

---

src/pages/play.astro

Closes https://github.com/WICG/webmonetization/issues/491
Add `?wa=walletAddressUrl` (multiple ok) to add link tags on page load. Matches validations like form (except must be URL, not payment pointers). If WM is not supported, tags are not added.
[Example](https://deploy-preview-492--webmonetization-preview.netlify.app/play/?wa=https://ilp.interledger-test.dev/sid&wa=https://ilp.interledger-test.dev/sid-mxn-1&wa=https://ilp.interledger-test.dev/sid)

feat(/play): add wallet addresses from URL parameters

---

.github/workflows/deploy.yml

`actions/upload-pages-artifact@v1` is using `actions/upload-artifact@v1` which is deprecated.

chore(ci/deploy): update actions version

---

astro.config.mjs
src/pages/index.astro
src/pages/install.astro
src/pages/tools/index.astro
src/pages/tools/link-tag.astro
src/pages/tools/prob-revshare.astro

- Move rev-share and linktag generators under /tools

chore: move all tools under /tools

---

src/components/pages/Footer.astro
src/components/pages/TopNav.astro

This fixes the spelling of "GitHub" to properly reflect the company name.
Additionally it also removes a trailing white space.

Fix GitHub capitalization typo

---

src/content/docs/developers/link-element-webpage.mdx
src/content/docs/developers/tools.mdx
src/partials/link-element-overview.mdx

specified "HTML" page in link element overview partial, changed page title of monetization link element page version that is in the wallet linking section. changed the "next" link at the bottom of the publishers tools page from the spec to the compatible wallets page, because the spec opens in a new window. this change at least keeps the reader in the docs.

docs: nav updates

---

astro.config.mjs

Removed stand-alone tutorials section from sidenav. Pages are now included in "Guides". Guides now has a subfolder called Test Web Monetization that has the three testing files within it.

docs: update left sidenav

---

package.json
src/components/docs/PageSidebar.astro

This PR bumps dependencies to the latest versions and also updates the PageSidebar implementation to replace deprecated features and update the glossary page URL.

chore: bump dependencies and update PageSidebar implementation

---

src/content/docs/developers/about-receiving.mdx
src/content/docs/docs.mdx
src/content/docs/guides/send-test-payments.mdx
src/content/docs/supporters/about-sending.mdx
src/content/docs/supporters/overview.mdx

After reviewing the Web Monetization docs as a whole, I’ve made a few changes and included them in this pull request. I’d like to explain my thought process and rationale behind these changes.
To me, there were a few permutations of word choices which are evident in the GitHub issue, the Web Monetization specification, and the Web Monetization documentation. Here’s the words in question:
- Streaming vs. continuous
- Payment vs. micropayment
Do we call it streaming payments, continuous micropayments, or something in between?
I recommend continuous payments, and here’s why:
- It’s aligned with the user interface. The toggle in the browser extension is “continuous payment” and choosing to keep the same terminology will help alleviate any confusion.
- “Streaming” itself is a difficult word, …

docs: consistent use of continuous payments

---

src/components/pages/TopNav.astro

Closes https://github.com/interledger/web-monetization-tools/issues/95 (originally reported there).
`/en` is 404
_(well I temporarily added a 301 redirect in Cloudflare)_

fix(TopNav): fix broken /en home page link

---

src/components/AnalyticsScript.astro
src/layouts/Base.astro

Fixes #575 
- Ensure `data-domains` attribute is added correctly.
- Move the script into its own component, otherwise Astro will process the script and remove all the custom attributes.
- Now the script is same as we'd have on Starlight docs.

fix: ensure analytics script markup is consistent & valid
